-- You can use this file to load seed data into the database using SQL statements
insert into Member (id, name, email, phone_number) values (0, 'John Smith', 'john.smith@mailinator.com', '2125551212')

--Question is the owner, so create first them associate answers
insert into Question (id, question) values (1, 'Quem foi o 1 Rei de Portugal?')
insert into Answer (id, answer, correctAnswer, questionId) values (1, 'Herman Jose', 'D. Afonso Henriques', 1)
insert into Answer (id, answer, correctAnswer, questionId) values (2, 'Cristiano Ronaldo', 'D. Afonso Henriques', 1)
insert into Answer (id, answer, correctAnswer, questionId) values (3, 'D. Dinis', 'D. Afonso Henriques', 1)
insert into Answer (id, answer, correctAnswer, questionId) values (4, 'D. Afonso Henriques', 'D. Afonso Henriques', 1)

insert into Question (id, question) values (2, 'Qual é a capital de Portugal?')
insert into Answer (id, answer, correctAnswer, questionId) values (5, 'Lisboa', 'Lisboa', 2)
insert into Answer (id, answer, correctAnswer, questionId) values (6, 'Porto', 'Lisboa', 2)
insert into Answer (id, answer, correctAnswer, questionId) values (7, 'Mirandela', 'Lisboa', 2)
insert into Answer (id, answer, correctAnswer, questionId) values (8, 'Aveiro', 'Lisboa', 2)

insert into Question (id, question) values (3, 'Onde joga actualmente Ibraimhovic?')
insert into Answer (id, answer, correctAnswer, questionId) values (9, 'A.C.Milan', 'Paris-Saint-German', 3)
insert into Answer (id, answer, correctAnswer, questionId) values (10, 'Paris-Saint-German', 'Paris-Saint-German', 3)
insert into Answer (id, answer, correctAnswer, questionId) values (11, 'F.C.Barcelona', 'Paris-Saint-German', 3)
insert into Answer (id, answer, correctAnswer, questionId) values (12, 'F.C.Aljustrel', 'Paris-Saint-German', 3)

insert into Question (id, question) values (4, 'Em que país se irá realizar o mundial de futebol de 2014?')
insert into Answer (id, answer, correctAnswer, questionId) values (13, 'Brasil', 'Brasil', 4)
insert into Answer (id, answer, correctAnswer, questionId) values (14, 'Botswana', 'Brasil', 4)
insert into Answer (id, answer, correctAnswer, questionId) values (15, 'Espanha', 'Brasil', 4)
insert into Answer (id, answer, correctAnswer, questionId) values (16, 'Vietname', 'Brasil', 4)

insert into Question (id, question) values (5, 'Em quais cidades marca presença a Universidade do Minho?')
insert into Answer (id, answer, correctAnswer, questionId) values (17, 'Porto. V.P.Âncora', 'Braga. Guimarães', 5)
insert into Answer (id, answer, correctAnswer, questionId) values (18, 'Braga. Guimarães', 'Braga. Guimarães', 5)
insert into Answer (id, answer, correctAnswer, questionId) values (19, 'V.Real. Braga', 'Braga. Guimarães', 5)
insert into Answer (id, answer, correctAnswer, questionId) values (20, 'Barcelos. V.Castelo', 'Braga. Guimarães', 5)

insert into Question (id, question) values (6, 'Qual o nome da série televisiva onde participou Pamela Anderson?')
insert into Answer (id, answer, correctAnswer, questionId) values (21, 'Baywatch', 'Baywatch', 6)
insert into Answer (id, answer, correctAnswer, questionId) values (22, 'Beverly Hills.90210', 'Baywatch', 6)
insert into Answer (id, answer, correctAnswer, questionId) values (23, 'Batman and Robin', 'Baywatch', 6)
insert into Answer (id, answer, correctAnswer, questionId) values (24, 'Dr. House', 'Baywatch', 6)

insert into Question (id, question) values (7, 'O que significa a palavra "felpudo"?')
insert into Answer (id, answer, correctAnswer, questionId) values (25, 'Doce', 'Peludo', 7)
insert into Answer (id, answer, correctAnswer, questionId) values (26, 'Querido', 'Peludo', 7)
insert into Answer (id, answer, correctAnswer, questionId) values (27, 'Amoroso', 'Peludo', 7)
insert into Answer (id, answer, correctAnswer, questionId) values (28, 'Peludo', 'Peludo', 7)

insert into Question (id, question) values (8, 'Por que nome é conhecido o vocalista dos Da Weasel?')
insert into Answer (id, answer, correctAnswer, questionId) values (29, 'Tetris', 'Pacman', 8)
insert into Answer (id, answer, correctAnswer, questionId) values (30, 'Super Mário', 'Pacman', 8)
insert into Answer (id, answer, correctAnswer, questionId) values (31, 'Pacman', 'Pacman', 8)
insert into Answer (id, answer, correctAnswer, questionId) values (32, 'Paco', 'Pacman', 8)

insert into Question (id, question) values (9, 'Quantos dias tem um ano bissexto?')
insert into Answer (id, answer, correctAnswer, questionId) values (33, '365', '366', 9)
insert into Answer (id, answer, correctAnswer, questionId) values (34, '356', '366', 9)
insert into Answer (id, answer, correctAnswer, questionId) values (35, '366', '366', 9)
insert into Answer (id, answer, correctAnswer, questionId) values (36, '355', '366', 9)

insert into Question (id, question) values (10, 'Qual é a primeira pessoa do presente indicativo do verbo "ler"?')
insert into Answer (id, answer, correctAnswer, questionId) values (37, 'Eu li', 'Eu leio', 10)
insert into Answer (id, answer, correctAnswer, questionId) values (38, 'Eu lerei', 'Eu leio', 10)
insert into Answer (id, answer, correctAnswer, questionId) values (39, 'Eu lia', 'Eu leio', 10)
insert into Answer (id, answer, correctAnswer, questionId) values (40, 'Eu leio', 'Eu leio', 10)

insert into Question (id, question) values (11, 'Como são conhecidos os lisboetas?')
insert into Answer (id, answer, correctAnswer, questionId) values (41, 'Estranhos', 'Alfacinhas', 11)
insert into Answer (id, answer, correctAnswer, questionId) values (42, 'Alfacetas', 'Alfacinhas', 11)
insert into Answer (id, answer, correctAnswer, questionId) values (43, 'Alface', 'Alfacinhas', 11)
insert into Answer (id, answer, correctAnswer, questionId) values (44, 'Alfacinhas', 'Alfacinhas', 11)

insert into Question (id, question) values (12, 'Como se chama à frase que formula uma pergunta?')
insert into Answer (id, answer, correctAnswer, questionId) values (45, 'Imperativa', 'Interrogativa', 12)
insert into Answer (id, answer, correctAnswer, questionId) values (46, 'Interrogativa', 'Interrogativa', 12)
insert into Answer (id, answer, correctAnswer, questionId) values (47, 'Exclamativa', 'Interrogativa', 12)
insert into Answer (id, answer, correctAnswer, questionId) values (48, 'Declarativa', 'Interrogativa', 12)

insert into Question (id, question) values (13, 'Que tipo de alimento é um tremoço?')
insert into Answer (id, answer, correctAnswer, questionId) values (49, 'Cereal', 'Leguminosa', 13)
insert into Answer (id, answer, correctAnswer, questionId) values (50, 'Fruto seco', 'Leguminosa', 13)
insert into Answer (id, answer, correctAnswer, questionId) values (51, 'Leguminosa', 'Leguminosa', 13)
insert into Answer (id, answer, correctAnswer, questionId) values (52, 'Enchido', 'Leguminosa', 13)

insert into Question (id, question) values (14, 'Qual o nome do companheiro da boneca Barbie?')
insert into Answer (id, answer, correctAnswer, questionId) values (53, 'Romeu', 'Ken', 14)
insert into Answer (id, answer, correctAnswer, questionId) values (54, 'David', 'Ken', 14)
insert into Answer (id, answer, correctAnswer, questionId) values (55, 'John', 'Ken', 14)
insert into Answer (id, answer, correctAnswer, questionId) values (56, 'Ken', 'Ken', 14)

insert into Question (id, question) values (15, 'Qual destes órgãos pertence ao sistema respiratório?')
insert into Answer (id, answer, correctAnswer, questionId) values (57, 'Laringe', 'Laringe', 15)
insert into Answer (id, answer, correctAnswer, questionId) values (58, 'Bexiga', 'Laringe', 15)
insert into Answer (id, answer, correctAnswer, questionId) values (59, 'Coração', 'Laringe', 15)
insert into Answer (id, answer, correctAnswer, questionId) values (60, 'Fígado', 'Laringe', 15)